//Batch Number : 67
//Dhairya Sangoi - 2012B4A7640P
//Gautam Singhania - 2012B4A7495P

#ifndef LEXERDEF_H_INCLUDED
#define LEXERDEF_H_INCLUDED

//states used in dfs
typedef enum enum_States {
	INIT, COMMENT, SYMUNDERSCORE, SYMUNDERSCOREM, SYMUNDERSCOREMA, SYMUNDERSCOREMAI,
	SYMHASH, SYMLT, SYMLTDASH, SYMLTDASHTWO, SYMGT, SYMEXCLAIM, SYMEQUAL, SYMAMPERSCENT, SYMAMPERSCENTTWO,
	SYMATTHERATE, SYMATTHERATETWO, DIGIT, DIGITDOT, DIGITDOTDIGIT, DIGITDOTDIGITTWO,

	BORD, C, CA, CAL, E, EL, ELS, EN, ENDI, ENDR, ENDRE, ENDREC, ENDRECO, ENDRECOR, ENDW, ENDWH, ENDWHI, ENDWHIL,
	G, GL, GLO, GLOB, GLOBA, I, IN, INP, INPU, L, LI, LIS, O, OU, OUT, OUTP, OUTPU, P, PA, PAR, PARA, PARAM,
	PARAME, PARAMET, PARAMETE, R, RE, REA, REC, RECO, RECOR, RET, RETU, RETUR, T, TH, THE, TY, TYP,
	W, WH, WHI, WHIL, WI, WIT, WR, WRI, WRIT,

	ID, IDCHAR, IDCHARDIGIT, FIELDID, MAIN, FUNCTIONID, FUNCTIONIDDIGITS, RECORDID,

	CALL, IF, ELSE, END, ENDIF, ENDRECORD, ENDWHILE, GLOBAL, INPUT, INT, LIST, OUTPUT, PARAMETER, PARAMETERS,
	RECORD, REAL, READ, RETURN, THEN, TYPE, WHILE, WITH, WRITE,

	ERRTONOTEALPHANUM, ERRTONOTESYM, ERRUNKNOWN}
State;

#endif // LEXERDEF_H_INCLUDED
