//Batch Number : 67
//Dhairya Sangoi - 2012B4A7640P
//Gautam Singhania - 2012B4A7495P

#ifndef LEXER_H_INCLUDED
#define LEXER_H_INCLUDED

//method to fill buffer
FILE *getStream(FILE *fp, char* B, int k);

//method to add token to token list
State addToken(tokenlist* ctr, int *isAdded, int *next_pos, trie* t, State* x, char* name_of_token, int lineno);

//method to tokenize the buffer generated by getStream method
tokenlist* getNextToken(char B[], State* state, int* lineno, trie *t, char *name_of_token);

//method to tokenize the file by breaking in parts and returning the tokenlist
tokenlist* caller_function(FILE* fp, int k, trie *t);

#endif // LEXER_H_INCLUDED
